//////////////////////////////////////////////////////////////////////
// This file was automatically generated by CLIF to run under Python 3
// Version 0.3
//////////////////////////////////////////////////////////////////////
// source: /pykaldi/tools/clif_backend/llvm/tools/clif/python/utils/proto_util.clif

#include <Python.h>

namespace clif_python_utils_proto__util_clifwrap {

bool Ready();
PyObject* Init();

}  // namespace clif_python_utils_proto__util_clifwrap

PyMODINIT_FUNC PyInit_proto_util(void) {
  if (!clif_python_utils_proto__util_clifwrap::Ready()) return nullptr;
  return clif_python_utils_proto__util_clifwrap::Init();
}
